### ISSUE TITLE
Cannot open connected app HTTP Error 503

### ISSUE THREAD

**Issue by Nat11** [salesforceidentity/heroku-identity-java#5]
Hello, i followed all the steps to create a connected app in my dev org, i exchanged metadata with heroku app but i receive this error when i run the app.
HTTP ERROR 503
Problem accessing /_saml. Reason:
    org.xml.sax.SAXParseExceptionpublicId: -//W3C//DTD HTML 4.01 Transitional//EN; systemId: http://www.w3.org/TR/html4/loose.dtd; lineNumber: 31; columnNumber: 3; The declaration for the entity "HTML.Version" must end with '>'.

![error](https://cloud.githubusercontent.com/assets/16664438/26409189/24ece7c4-40a0-11e7-91bb-902cd938ae7e.png)

**Comment by rhooseboy** [comment]
Hi - getting an error trying to deploy to Heroku.

[INFO] ------------------------------------------------------------------------
       [INFO] BUILD FAILURE
       [INFO] ------------------------------------------------------------------------
       [INFO] Total time:  2.937 s
       [INFO] Finished at: 2020-10-21T13:26:42Z
       [INFO] ------------------------------------------------------------------------
       [ERROR] Failed to execute goal on project herokusamlsp: Could not resolve dependencies for project com.example:herokusamlsp:jar:1.0: Could not find artifact org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:8.5.55 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
       [ERROR] 
       [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
       [ERROR] Re-run Maven using the -X switch to enable full debug logging.
       [ERROR] 
       [ERROR] For more information about the errors and possible solutions, please read the following articles:
       [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
 !     ERROR: Failed to build app with Maven

Any ideas? Thanks
