### ISSUE TITLE
Error deploying to Heroku

### ISSUE THREAD

**Issue by rhooseboy** [salesforceidentity/heroku-identity-java#8]
Hi - getting an error trying to deploy to Heroku.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.937 s
[INFO] Finished at: 2020-10-21T13:26:42Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project herokusamlsp: Could not resolve dependencies for project com.example:herokusamlsp:jar:1.0: Could not find artifact org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:8.5.55 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
! ERROR: Failed to build app with Maven

Any ideas? Thanks

**Comment by davidjbrossard** [comment]
I updated the pom.xml to the latest recommended version due to a possible vulnerability in the previous version of Tomcat. This is what the pom previously contained: <tomcat.version>8.0.28</tomcat.version>

And this is what I changed it to:
        <tomcat.version>8.5.55</tomcat.version>

Can you check whether you can get it to work on the older version?

**Comment by davidjbrossard** [comment]
So looking at Maven Central, I can see that tomcat-embed-logging-juli doesn't have an 8.5.55 version.

https://repo1.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-logging-juli/

I ran through all the dependencies and saw that they all have an 8.5.2 version so I'll update the pom to that. Ideally you'd probably want to update each component individually to make sure you have the latest of each that are compatible..

**Comment by rhooseboy** [comment]
Many thanks for your quick response. That fixed it.
